name: CI - Intégration Continue

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  Code-Quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Installer htmlhint
      - name: Install HTMLHint
        run: npm install -g htmlhint

      # 4. Vérifier que src/ existe
      - name: Check src folder
        run: |
          if [ ! -d "src" ]; then
            echo "❌ Dossier src/ introuvable"
            exit 1
          fi
          echo "✅ Dossier src/ trouvé"
          ls src/

      # 5. Valider le HTML
      - name: Validate HTML
        run: |
          if ls src/*.html 1>/dev/null 2>&1; then
            htmlhint "src/**/*.html"
            echo "✅ HTML valide"
          else
            echo "❌ Aucun fichier HTML dans src/"
            exit 1
          fi